create table ACT_RU_EVENT_SUBSCR (
    ID_ VARCHAR(64) not null,
    REV_ integer,
    EVENT_TYPE_ VARCHAR(255) not null,
    EVENT_NAME_ VARCHAR(255),
    EXECUTION_ID_ VARCHAR(64),
    PROC_INST_ID_ VARCHAR(64),
    ACTIVITY_ID_ VARCHAR(64),
    CONFIGURATION_ VARCHAR(255),
    CREATED_ TIMESTAMP(6) not null,
    PROC_DEF_ID_ VARCHAR(64),
    SUB_SCOPE_ID_ VARCHAR(64),
    SCOPE_ID_ VARCHAR(64),
    SCOPE_DEFINITION_ID_ VARCHAR(64),
    SCOPE_DEFINITION_KEY_ VARCHAR(255),
    SCOPE_TYPE_ VARCHAR(64),
    LOCK_TIME_ TIMESTAMP(6),
    LOCK_OWNER_ VARCHAR(255),
    TENANT_ID_ VARCHAR(255) DEFAULT '',
    primary key (ID_)
);

create index ACT_IDX_EVENT_SUBSCR_CONFIG_ on ACT_RU_EVENT_SUBSCR(CONFIGURATION_);
create index ACT_IDX_EVENT_SUBSCR on ACT_RU_EVENT_SUBSCR(EXECUTION_ID_);
create index ACT_IDX_EVENT_SUBSCR_SCOPEREF_ on ACT_RU_EVENT_SUBSCR(SCOPE_ID_, SCOPE_TYPE_);

insert into ACT_GE_PROPERTY values ('eventsubscription.schema.version', '7.0.1.1', 1);
